# Generated by Django 3.1.2 on 2020-10-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('quantinty', models.IntegerField()),
                ('category', models.CharField(choices=[('laptops', 'laptop'), ('smartphone', 'smartphne'), ('others', 'others')], default='laptops', max_length=100)),
                ('NewandUsed', models.CharField(choices=[('used', 'used'), ('new', 'new')], default='new', max_length=10)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM', models.CharField(default='4GB', max_length=50)),
                ('internal', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('Defficiency', models.TextField(max_length=1000)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selling.products')),
            ],
        ),
    ]
